version: '3.1'

# TODO update this to pull from env vars
name: cjresume-dev
services:
  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass

  mysql-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-adminer:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/

  api:
    image: curtisgrjones/cjweb-api
    ports:
      - 8000:8000
    environment:
      MONGO_USER: root
      MONGO_PASS: pass
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  app:
    image: curtisgrjones/cjweb-app
    ports:
      - 3000:3000

  nginx:
    image: curtisgrjones/cjweb-nginx
    ports:
      - 80:80