version: '3.1'

name: cjresume-dev
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d

  mysql-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-adminer:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/

  api:
    image: curtisgrjones/cjweb-api
    ports:
      - 8000:8000
    env_file:
      - .env.api
    environment:
      PORT: 8000

  app:
    image: curtisgrjones/cjweb-app
    ports:
      - 3000:3000
    env_file:
      - .env.app

  nginx:
    image: curtisgrjones/cjweb-nginx
    ports:
      - 80:80