version: '3.1'

# TODO update this to pull from env vars
name: cjresume-prod
services:
  api:
    image: curtisgrjones/cjweb-api
    restart: always
    ports:
      - 8000:8000
    env_file:
      # TODO use a secrets manager
      - .env.api
    environment:
      PORT: 8000

  app:
    image: curtisgrjones/cjweb-app
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.app

  nginx:
    image: curtisgrjones/cjweb-nginx
    restart: always
    ports:
      - 80:80