version: '3.1'

# TODO use a secrets manager
name: cjresume-prod
services:
  api:
    image: curtisgrjones/cjweb-api
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env.api
    environment:
      PORT: 8000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M

  app:
    image: curtisgrjones/cjweb-app
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.app
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 20M

  nginx:
    image: curtisgrjones/cjweb-nginx
    restart: always
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 6M